---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/
- examples/
